
module.exports.knifeDefinitionIndex = {

  WEAPON_KNIFE_CT: 42,
  WEAPON_KNIFE_T: 59,
  WEAPON_KNIFE_BAYONET: 500,
  WEAPON_KNIFE_CLASSIC: 503,
  WEAPON_KNIFE_FLIP: 505,
  WEAPON_KNIFE_GUT: 506,
  WEAPON_KNIFE_KARAMBIT: 507,
  WEAPON_KNIFE_M9_BAYONET: 508,
  WEAPON_KNIFE_HUNTSMAN: 509,
  WEAPON_KNIFE_FALCHION: 512,
  WEAPON_KNIFE_BOWIE: 514,
  WEAPON_KNIFE_BUTTERFLY: 515,
  WEAPON_KNIFE_DAGGERS: 516,
  WEAPON_KNIFE_PARACORD: 517,
  WEAPON_KNIFE_URSUS: 519,
  WEAPON_KNIFE_CANIS: 518,
  WEAPON_KNIFE_NAVAJA: 520,
  WEAPON_KNIFE_OUTDOOR: 521,
  WEAPON_KNIFE_STILETTO: 522,
  WEAPON_KNIFE_TALON: 523,
  WEAPON_KNIFE_SKELETON: 525,
};

module.exports.knifeAnimationIndex = {


  
};

module.exports.classID = {
  
  // ONLY ADD THE CLASS IDS THAT YOU ARE GOING TO USE!
  // ONLY ADD THE CLASS IDS THAT YOU ARE GOING TO USE!
  // ONLY ADD THE CLASS IDS THAT YOU ARE GOING TO USE!
  // ONLY ADD THE CLASS IDS THAT YOU ARE GOING TO USE!
}